language: python

python:
  - "3.6.1"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - pip install coverage

before_script:
  - sudo -u postgres createdb bucket
  - sudo -u postgres createdb test_bucketlist

# command to run the tests
script:
  - nose2 -v --with-coverage

after_script:
  - sudo -u postgres dropdb bucket
  - sudo -u postgres dropdb test_bucketlist

after_success:
  - coveralls